const Ukr = [
  {
    GID_1: 'UKR.1_1',
    NAME_1: 'Cherkasy',
    NL_NAME_1: 'Черкаська',
    value: 27,
  },
  {
    GID_1: 'UKR.2_1',
    NAME_1: 'Chernihiv',
    NL_NAME_1: 'Чернігівська',
    value: 8,
  },
  {
    GID_1: 'UKR.3_1',
    NAME_1: 'Chernivtsi',
    NL_NAME_1: 'Чернівецька',
    value: 0,
  },
  {
    GID_1: 'UKR.4_1',
    NAME_1: 'Crimea',
    NL_NAME_1: 'АР Крим',
    value: 0,
  },
  {
    GID_1: 'UKR.5_1',
    NAME_1: 'Dnipro',
    NL_NAME_1: 'Дніпропетровська',
    value: 1,
  },
  {
    GID_1: 'UKR.6_1',
    NAME_1: 'Donetsk',
    NL_NAME_1: 'Донецька',
    value: 3,
  },
  {
    GID_1: 'UKR.7_1',
    NAME_1: 'Ivano-Frankivsk',
    NL_NAME_1: 'Івано-Франківська',
    value: 2,
  },
  {
    GID_1: 'UKR.8_1',
    NAME_1: 'Kharkiv',
    NL_NAME_1: 'Харківська',
    value: 2,
  },
  {
    GID_1: 'UKR.9_1',
    NAME_1: 'Kherson',
    NL_NAME_1: 'Херсонська',
    value: 0,
  },
  {
    GID_1: 'UKR.10_1',
    NAME_1: 'Khmelnytskyy',
    NL_NAME_1: 'Хмельницька',
    value: 0,
  },
  {
    GID_1: 'UKR.11_1',
    NAME_1: 'Kyiv',
    NL_NAME_1: 'Київська',
    value: 0,
  },
  {
    GID_1: 'UKR.12_1',
    NAME_1: 'Kyiv сity',
    NL_NAME_1: 'Київ',
    value: 21,
  },
  {
    GID_1: 'UKR.13_1',
    NAME_1: 'Kirovohrad',
    NL_NAME_1: 'Кіровоградська',
    value: 8,
  },
  {
    GID_1: 'UKR.14_1',
    NAME_1: 'Lviv',
    NL_NAME_1: 'Львівська',
    value: 0,
  },
  {
    GID_1: 'UKR.15_1',
    NAME_1: 'Luhansk',
    NL_NAME_1: 'Луганська',
    value: 13,
  },
  {
    GID_1: 'UKR.16_1',
    NAME_1: 'Mykolayiv',
    NL_NAME_1: 'Миколаївська',
    value: 10,
  },
  {
    GID_1: 'UKR.17_1',
    NAME_1: 'Odesa',
    NL_NAME_1: 'Одеська',
    value: 5,
  },
  {
    GID_1: 'UKR.18_1',
    NAME_1: 'Poltava',
    NL_NAME_1: 'Полтавська',
    value: 31,
  },
  {
    GID_1: 'UKR.19_1',
    NAME_1: 'Rivne',
    NL_NAME_1: 'Рівненська',
    value: 3,
  },
  {
    GID_1: 'UKR.20_1',
    NAME_1: 'Sevastopol city',
    NL_NAME_1: 'Севастополь',
    value: 0,
  },
  { GID_1: 'UKR.21_1', NAME_1: 'Sumy', NL_NAME_1: 'Сумська', value: 2 },
  {
    GID_1: 'UKR.22_1',
    NAME_1: 'Ternopil',
    NL_NAME_1: 'Тернопільська',
    value: 8,
  },
  {
    GID_1: 'UKR.23_1',
    NAME_1: 'Vinnytsia',
    NL_NAME_1: 'Вінницька',
    value: 7,
  },
  {
    GID_1: 'UKR.24_1',
    NAME_1: 'Volyn',
    NL_NAME_1: 'Волинська',
    value: 0,
  },
  {
    GID_1: 'UKR.25_1',
    NAME_1: 'Zakarpattia',
    NL_NAME_1: 'Закарпатська',
    value: 0,
  },
  {
    GID_1: 'UKR.26_1',
    NAME_1: 'Zaporizhzhia',
    NL_NAME_1: 'Запорізька',
    value: 3,
  },
  {
    GID_1: 'UKR.27_1',
    NAME_1: 'Zhytomyr',
    NL_NAME_1: 'Житомирська',
    value: 6,
  },
];

export default Ukr;
